application: wjgdownload
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.app
  
- url: /api
  script: api.app
  
- url: /favicon\.ico
  script: favicon.app
  
- url: /.*
  script: notfound.app
